---
type: "camera"
sensor_class: "PySpinCamera"
model: "FLIR-BFS-PGE-50S50C"
sensor: "Sony IMX264 2/3"
serial: "24131919"
width: 2448
height: 2048
fps: 20
jpg_compression_pct: 0
interpolate: 2
io_threads: 2
calibration:
  channel_order: "bgr"
  intrinsics:
    fx: 1448
    fy: 1448
    u: 1224  # width / 2
    v: 1024  # height / 2
    g: 0
  extrinsics:
    dx: 0
    dy: 0
    dz: 0
    qx: 0
    qy: 0
    qz: 0
backend:
  transport: "ipc"
  host: localhost
  port: 5550
  bind: False
ip: 192.168.1.3
verbose: True
debug: False